/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import adapter.adapterSidang;
import com.Sidang;
import exec.ExecuteMahasiswa;
import exec.ExecuteSidang;
import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;

/**
 *
 * @author D3LL
 */
public class formSidang extends javax.swing.JFrame {

    /**
     * Creates new form Sidang
     */
    public formSidang() {
        initComponents();
        displayall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tf_idsidang = new javax.swing.JTextField();
        tf_ruangan = new javax.swing.JTextField();
        tf_idKp = new javax.swing.JTextField();
        btn_main = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSidang = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        dp_tggl = new org.jdesktop.swingx.JXDatePicker();

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tf_idsidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, -1));
        getContentPane().add(tf_ruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, -1));

        tf_idKp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idKpActionPerformed(evt);
            }
        });
        getContentPane().add(tf_idKp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, -1));

        btn_main.setText("Main Menu");
        btn_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainActionPerformed(evt);
            }
        });
        getContentPane().add(btn_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIDANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Sidang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID KP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ruangan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        tblSidang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Sidang", "Tanggal", "Ruangan", "ID KP"
            }
        ));
        tblSidang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSidangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSidang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 370, 180));

        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, -1));

        btn_edit.setText("Edit");
        btn_edit.setEnabled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 80, -1));

        dp_tggl.setDate(new java.util.Date()
        );
        dp_tggl.setFormats("yyyy-MM-dd");
        dp_tggl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_tgglActionPerformed(evt);
            }
        });
        getContentPane().add(dp_tggl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void displayall(){
        adapterSidang ag = new adapterSidang();
        Object[][] mysdg = ag.getAllGuru();
        tblSidang.setModel(new javax.swing.table.DefaultTableModel(
            mysdg,
            new String [] {
                "ID Sidang", "Tanggal", "Ruangan", "ID KP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSidang);

    }
    private void btn_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainActionPerformed
        // TODO add your handling code here:
        MainMenu n = new MainMenu();
        n.setVisible(true);
        this.setVisible(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_mainActionPerformed

    private void tblSidangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSidangMouseClicked
        // TODO add your handling code here:
        int row = tblSidang.getSelectedRow();
        
        tf_idsidang.setText(tblSidang.getValueAt(row, 0).toString());
        try{
          DefaultTableModel model = (DefaultTableModel)tblSidang.getModel();
          int index = tblSidang.getSelectedRow();
          Date tgl = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(row, 1));
          dp_tggl.setDate(tgl);
        } catch(ParseException ex){
            Logger.getLogger(formSidang.class.getName()).log(Level.SEVERE, null, ex);
        }
        tf_ruangan.setText(tblSidang.getValueAt(row, 2).toString());
        tf_idKp.setText(tblSidang.getValueAt(row, 3).toString());
        btn_edit.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_simpan.setEnabled(false);
    }//GEN-LAST:event_tblSidangMouseClicked

    private void tf_idKpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idKpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idKpActionPerformed

    private void dp_tgglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_tgglActionPerformed
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
    }//GEN-LAST:event_dp_tgglActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        Sidang sdg = new Sidang();
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dFormat.format(dp_tggl.getDate());
        
        sdg.setIdsidang(tf_idsidang.getText().toString());
        sdg.setTanggal(date);
        sdg.setRuangan(tf_ruangan.getText().toString());
        sdg.setIdkp(tf_idKp.getText().toString());
        
        ExecuteSidang es = new ExecuteSidang();
        String Hasil = es.InsertSidang(sdg);
        JOptionPane.showMessageDialog(rootPane, Hasil);
        displayall();

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        Sidang sdg = new Sidang();
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dFormat.format(dp_tggl.getDate());
//        mengambil nilai dari komponen
        sdg.setIdsidang(tf_idsidang.getText().toString());
        sdg.setTanggal(date);
        sdg.setRuangan(tf_ruangan.getText().toString());
        sdg.setIdkp(tf_idKp.getText().toString());
        
        ExecuteSidang em = new ExecuteSidang();
        String Hasil = em.UpdateSidang(sdg);
        JOptionPane.showMessageDialog(rootPane, Hasil);
        if(Hasil=="Berhasil"){
            tf_idsidang.setText("");
            tf_ruangan.setText("");
            tf_idKp.setText("");
            displayall();
        }
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int column= tblSidang.getSelectedColumn();
        int row = tblSidang.getSelectedRow();
        if(column>=0){
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Are You Sure?");
            if (confirm==0){
                System.out.println("Konfirmasi: "+confirm);
                Object ID_Sidang = tblSidang.getModel().getValueAt(row, 0);
                ExecuteSidang es = new ExecuteSidang();
                es.DeleteSidang((String) ID_Sidang);
                JOptionPane.showMessageDialog(rootPane, "Deleted");
                
                tf_idsidang.setText("");
                tf_ruangan.setText("");
                tf_idKp.setText("");
               
            } else if (confirm==1){
                tf_idsidang.setText("");
                tf_ruangan.setText("");
                tf_idKp.setText("");
                displayall();
            }
            displayall();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Data");
        }
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_deleteActionPerformed
    public static Date getTglFromTbl(JTable table, int kolom){
        JTable tabel = table;
        String str_tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), kolom));
        Date tanggal = null;
        try {
            Date tgl = new SimpleDateFormat("yyyy-MM-dd").parse(str_tgl);
        } catch (ParseException ex) {
            Logger.getLogger(formSidang.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tanggal;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formSidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formSidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formSidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formSidang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formSidang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_main;
    private javax.swing.JButton btn_simpan;
    private org.jdesktop.swingx.JXDatePicker dp_tggl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblSidang;
    private javax.swing.JTextField tf_idKp;
    private javax.swing.JTextField tf_idsidang;
    private javax.swing.JTextField tf_ruangan;
    // End of variables declaration//GEN-END:variables
}
