/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import adapter.adapterMahasiswa;
import com.Mahasiswa;
import exec.ExecuteMahasiswa;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Adri
 */
public class formMahasiswaa extends javax.swing.JFrame {

    /**
     * Creates new form Mahasiswaa
     */
    public formMahasiswaa() {
        initComponents();
        displayall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        tf_nrp = new javax.swing.JTextField();
        tf_nama = new javax.swing.JTextField();
        tf_jurusan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txtalamat = new javax.swing.JTextArea();
        tf_notelp = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_main = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMhsw = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_nrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nrpActionPerformed(evt);
            }
        });
        tf_nrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_nrpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nrpKeyTyped(evt);
            }
        });
        getContentPane().add(tf_nrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 61, 210, 30));

        tf_nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 105, 210, 30));

        tf_jurusan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_jurusanKeyTyped(evt);
            }
        });
        getContentPane().add(tf_jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 156, 210, 30));

        Txtalamat.setColumns(20);
        Txtalamat.setRows(5);
        jScrollPane1.setViewportView(Txtalamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 204, 210, -1));

        tf_notelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_notelpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_notelpKeyTyped(evt);
            }
        });
        getContentPane().add(tf_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 318, 210, 30));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 83, -1));

        btn_edit.setText("Edit");
        btn_edit.setEnabled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 80, -1));

        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 90, -1));

        btn_main.setText("Main Menu");
        btn_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainActionPerformed(evt);
            }
        });
        getContentPane().add(btn_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 102, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAHASISWA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Telp");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 318, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 214, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 166, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 112, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NRP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 61, -1, -1));

        tblMhsw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NRP", "Nama", "Jurusan", "Alamat", "No Telp"
            }
        ));
        tblMhsw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMhswMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMhsw);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 520, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void displayall(){
        adapterMahasiswa ag = new adapterMahasiswa();
        Object[][] mymhs = ag.getAllGuru();
        tblMhsw.setModel(new javax.swing.table.DefaultTableModel(
            mymhs,
            new String [] {
                "NRP", "Nama", "Jurusan", "Alamat", "No Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMhsw);

    }
    private void tf_nrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nrpActionPerformed

    private void btn_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainActionPerformed
        // TODO add your handling code here:
        MainMenu n = new MainMenu();
        n.setVisible(true);
        this.setVisible(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_mainActionPerformed

    private void tblMhswMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMhswMouseClicked
        // TODO add your handling code here:
        int row = tblMhsw.getSelectedRow();
        tf_nrp.setText(tblMhsw.getValueAt(row, 0).toString());
        tf_nama.setText(tblMhsw.getValueAt(row, 1).toString());
        tf_jurusan.setText(tblMhsw.getValueAt(row, 2).toString());
        Txtalamat.setText(tblMhsw.getValueAt(row, 3).toString());
        tf_notelp.setText(tblMhsw.getValueAt(row, 4).toString());
        btn_edit.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_simpan.setEnabled(false);
    }//GEN-LAST:event_tblMhswMouseClicked

    private void tf_nrpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nrpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nrpKeyPressed

    private void tf_notelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_notelpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_notelpKeyPressed

    private void tf_nrpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nrpKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))
            || (vchar==KeyEvent.VK_BACK_SPACE)
            || (vchar==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_tf_nrpKeyTyped

    private void tf_jurusanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jurusanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_jurusanKeyTyped

    private void tf_notelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_notelpKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))
            || (vchar==KeyEvent.VK_BACK_SPACE)
            || (vchar==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_tf_notelpKeyTyped

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhs = new Mahasiswa();
        mhs.setNRP(tf_nrp.getText().toString());
        mhs.setNama(tf_nama.getText().toString());
        mhs.setJurusan(tf_jurusan.getText().toString());
        mhs.setAlamat(Txtalamat.getText().toString());
        mhs.setNoHp(tf_notelp.getText().toString());
 
        ExecuteMahasiswa em = new ExecuteMahasiswa();
        String Hasil = em.InsertMahasiswa(mhs);
        JOptionPane.showMessageDialog(rootPane, Hasil);
        displayall();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
         Mahasiswa mhs = new Mahasiswa();
//        mengambil nilai dari komponen
        mhs.setNRP(tf_nrp.getText().toString());
        mhs.setNama(tf_nama.getText().toString());
        mhs.setJurusan(tf_jurusan.getText().toString());
        mhs.setAlamat(Txtalamat.getText().toString());
        mhs.setNoHp(tf_notelp.getText().toString());
        
        ExecuteMahasiswa em = new ExecuteMahasiswa();
        String Hasil = em.UpdateMahasiswa(mhs);
        JOptionPane.showMessageDialog(rootPane, Hasil);
        if(Hasil=="Berhasil"){
            tf_nrp.setText("");
            tf_nama.setText("");
            tf_jurusan.setText("");
            Txtalamat.setText("");
            tf_notelp.setText("");
            displayall();
            btn_edit.setEnabled(false);
            btn_delete.setEnabled(false);
            btn_simpan.setEnabled(true);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int column= tblMhsw.getSelectedColumn();
        int row = tblMhsw.getSelectedRow();
        if(column>=0){
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Are You Sure?");
            if (confirm==0){
                System.out.println("Konfirmasi: "+confirm);
                Object Nrp = tblMhsw.getModel().getValueAt(row, 0);
                ExecuteMahasiswa em = new ExecuteMahasiswa();
                em.DeleteMahasiswa((String) Nrp);
                JOptionPane.showMessageDialog(rootPane, "Deleted");
                tf_nrp.setText("");
                tf_nama.setText("");
                tf_jurusan.setText("");
                Txtalamat.setText("");
                tf_notelp.setText("");
            } else if (confirm==1){
                tf_nrp.setText("");
                tf_nama.setText("");
                tf_jurusan.setText("");
                Txtalamat.setText("");
                tf_notelp.setText("");
                displayall();
            }
            displayall();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Data");
        }
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMahasiswaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMahasiswaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMahasiswaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMahasiswaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMahasiswaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Txtalamat;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_main;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMhsw;
    private javax.swing.JTextField tf_jurusan;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_notelp;
    private javax.swing.JTextField tf_nrp;
    // End of variables declaration//GEN-END:variables
}
