/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.Dosen;
import com.KP;
import com.Pembimbing;
import com.Perusahaan;
import exec.ExecuteDosen;
import exec.ExecuteKP;
import exec.ExecutePembimbing;
import exec.ExecutePerusahaan;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Adri
 */
public class formKP extends javax.swing.JFrame {
            private void tampilData1(){
            ExecuteDosen exed = new ExecuteDosen();
            List<Dosen> allDsn = exed.getAll();
            Object[][] datadsn = new Object[allDsn.size()][4];
            int row = 0;
            for(Dosen dsn : allDsn){
                datadsn[row][0] = dsn.getNidn();
                datadsn[row][1] = dsn.getNama();
                datadsn[row][2] = dsn.getTgllahir();
                datadsn[row][3] = dsn.getJabatanakademik();
                row++;
            }   
            jTable5 = new javax.swing.JTable();
            jTable5.setModel(new javax.swing.table.DefaultTableModel(
            datadsn,
                new String [] {
                    "NIDN", "Nama", "Tanggal Lahir", "Jabatan Akademik"
                }
        ));
            jScrollPane5.setViewportView(jTable5);
    }   
            private void tampilData2(){
            ExecutePerusahaan ep = new ExecutePerusahaan();
            List<Perusahaan> allPrs = ep.getPrs();
            Object[][] dataprs = new Object[allPrs.size()][4];
            int row = 0;
            for(Perusahaan prs : allPrs){
                dataprs[row][0] = prs.getIdPerusahaan();
                dataprs[row][1] = prs.getNamaPerusahaan();
                dataprs[row][2] = prs.getAlamatPerusahaan();
                dataprs[row][3] = prs.getTlpPerusahaan();
                row++;
            }   
            jTable4 = new javax.swing.JTable();
            jTable4.setModel(new javax.swing.table.DefaultTableModel(
            dataprs,
                new String [] {
                    "ID", "Nama", "Alamat", "No TELEPON"
                }
        ));
            jScrollPane4.setViewportView(jTable4);
    }   
            private void tampilData3(){
            ExecutePembimbing epm = new ExecutePembimbing();
            List<Pembimbing> allPmb = epm.getPmb();
            Object[][] datapmb = new Object[allPmb.size()][3];
            int row = 0;
            for(Pembimbing pmb : allPmb){
                datapmb[row][0] = pmb.getIdPmb();
                datapmb[row][1] = pmb.getNamaPmb();
                datapmb[row][2] = pmb.getTlpPmb();
                row++;
            }   
            jTable1 = new javax.swing.JTable();
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            datapmb,
                new String [] {
                    "ID", "Nama", "No TELEPON",
                }
        ));
            jScrollPane1.setViewportView(jTable1);
    } 
     private void tampilData(){
            ExecuteKP ek = new ExecuteKP();
            List<KP> allK = ek.getKP();
            Object[][] datakp = new Object[allK.size()][5];
            int row = 0;
            for(KP k : allK){
                datakp[row][0] = k.getIdKp();
                datakp[row][1] = k.getNrp();
                datakp[row][2] = k.getIdPmb();
                datakp[row][3] = k.getIdPerusahaan();
                datakp[row][4] = k.getNidn();

                row++;
            }   
            jTable2 = new javax.swing.JTable();

            jTable2.setModel(new javax.swing.table.DefaultTableModel(
            datakp,
                new String [] {
                    "ID KP", "NRP", "ID PEMBIMBING", "ID PERUSAHAAN", "NIDN",
                }

        ));
            jScrollPane2.setViewportView(jTable2);
    }   
    public formKP() {
        initComponents();
        tampilData();
        tampilData1();
        tampilData2();
        tampilData3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_idkp = new javax.swing.JTextField();
        tf_pmb = new javax.swing.JTextField();
        tf_nrp = new javax.swing.JTextField();
        tf_perusahaan = new javax.swing.JTextField();
        tf_dsn = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        btn_main = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 0, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID KP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 61, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NRP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 23, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID PEMBIMBING");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID PERUSAHAAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIDN DOSEN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disahkan oleh:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        tf_idkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idkpActionPerformed(evt);
            }
        });
        tf_idkp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_idkpKeyPressed(evt);
            }
        });
        getContentPane().add(tf_idkp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 150, -1));

        tf_pmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pmbActionPerformed(evt);
            }
        });
        getContentPane().add(tf_pmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, -1));

        tf_nrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nrpActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, -1));

        tf_perusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_perusahaanActionPerformed(evt);
            }
        });
        getContentPane().add(tf_perusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, -1));

        tf_dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dsnActionPerformed(evt);
            }
        });
        getContentPane().add(tf_dsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 67, -1));

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 67, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID PEMBIMBING", "NAMA", "NO TELEPON"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, 153));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA KP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID KP", "NRP", "ID PEMBIMBING", "ID PERUSAHAAN", "NIDN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 153));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATA PEMBIMBING");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAMA", "ALAMAT", "NO TELEPON"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setEnabled(false);
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, 153));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DATA PERUSAHAAN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATA DOSEN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, -1, 20));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIDN", "NAMA", "TANGGAL LAHIR", "JABATAN AKADEMIK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.setEnabled(false);
        jScrollPane5.setViewportView(jTable5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, -1, 153));

        btn_main.setText("Main Menu");
        btn_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainActionPerformed(evt);
            }
        });
        getContentPane().add(btn_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\SEMESTER 4\\Pengolahan Citra Digital\\Gambar\\black-background_00313351.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idkpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idkpActionPerformed

    private void tf_pmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pmbActionPerformed

    private void tf_nrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nrpActionPerformed

    private void tf_perusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_perusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_perusahaanActionPerformed

    private void tf_dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dsnActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        KP k = new KP();
        k.setNrp(tf_nrp.getText().toString());
        k.setIdKp(tf_idkp.getText().toString());
        k.setIdPmb(tf_pmb.getText().toString());
        k.setIdPerusahaan(tf_perusahaan.getText().toString());
        k.setNidn(tf_dsn.getText().toString());
 
        ExecuteKP ek = new ExecuteKP();
        String Hasil = ek.InsertKP(k);
        JOptionPane.showMessageDialog(rootPane, Hasil);
        tampilData();
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainActionPerformed
        // TODO add your handling code here:
        MainMenu n = new MainMenu();
        n.setVisible(true);
        this.setVisible(false);
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_mainActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        KP k = new KP();
//        mengambil nilai dari komponen
        k.setIdKp(tf_idkp.getText().toString());
        k.setNrp(tf_nrp.getText().toString());
        k.setIdPmb(tf_pmb.getText().toString());
        k.setIdPerusahaan(tf_perusahaan.getText().toString());
        k.setNidn(tf_dsn.getText().toString());
        
        ExecuteKP ek = new ExecuteKP();
        String Hasil = ek.UpdateKP(k);
        JOptionPane.showMessageDialog(rootPane, Hasil);
        if(Hasil=="Berhasil"){
            tf_idkp.setText("");
            tf_nrp.setText("");
            tf_pmb.setText("");
            tf_perusahaan.setText("");
            tf_dsn.setText("");
            tampilData();
            btn_edit.setEnabled(false);
            btn_delete.setEnabled(false);
            btn_simpan.setEnabled(true);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int column= jTable2.getSelectedColumn();
        int row = jTable2.getSelectedRow();
        if(column>=0){
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Are You Sure?");
            if (confirm==0){
                System.out.println("Konfirmasi: "+confirm);
                Object idKp = jTable2.getModel().getValueAt(row, 0);
                ExecuteKP ek = new ExecuteKP();
                ek.DeleteKP((String) idKp);
                JOptionPane.showMessageDialog(rootPane, "Deleted");
                tf_idkp.setText("");
                tf_nrp.setText("");
                tf_pmb.setText("");
                tf_perusahaan.setText("");
                tf_dsn.setText("");
            } else if (confirm==1){
                tf_idkp.setText("");
                tf_nrp.setText("");
                tf_pmb.setText("");
                tf_perusahaan.setText("");
                tf_dsn.setText("");
                tampilData();
            }
            tampilData();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Data");
        }
        btn_edit.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        tf_idkp.setText(jTable2.getValueAt(row, 0).toString());
        tf_nrp.setText(jTable2.getValueAt(row, 0).toString());
        tf_pmb.setText(jTable2.getValueAt(row, 0).toString());
        tf_perusahaan.setText(jTable2.getValueAt(row, 0).toString());
        tf_dsn.setText(jTable2.getValueAt(row, 0).toString());
        btn_edit.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_simpan.setEnabled(false);
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void tf_idkpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_idkpKeyPressed
        // TODO add your handling code here:
                char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))
            || (vchar==KeyEvent.VK_BACK_SPACE)
            || (vchar==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_tf_idkpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formKP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formKP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formKP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formKP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formKP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_main;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField tf_dsn;
    private javax.swing.JTextField tf_idkp;
    private javax.swing.JTextField tf_nrp;
    private javax.swing.JTextField tf_perusahaan;
    private javax.swing.JTextField tf_pmb;
    // End of variables declaration//GEN-END:variables
}
