/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author D3LL
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_dsn = new javax.swing.JButton();
        btn_mhs = new javax.swing.JButton();
        btn_perusahaan = new javax.swing.JButton();
        btn_sidang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_pmb = new javax.swing.JButton();
        btn_kp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_dsn.setText("Dosen");
        btn_dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dsnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, 50));

        btn_mhs.setText("Mahasiswa");
        btn_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mhsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, 50));

        btn_perusahaan.setText("Perusahaan");
        btn_perusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perusahaanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_perusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 140, 50));

        btn_sidang.setText("Sidang");
        btn_sidang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sidangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KERJA PRAKTEK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btn_pmb.setText("Pembimbing");
        btn_pmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pmbActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, 50));

        btn_kp.setText("KP");
        btn_kp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\SEMESTER 4\\Pengolahan Citra Digital\\Gambar\\black-background_00313351.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dsnActionPerformed
        // TODO add your handling code here:
        formDosen n = new formDosen();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_dsnActionPerformed

    private void btn_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mhsActionPerformed
        // TODO add your handling code here:
        formMahasiswaa n = new formMahasiswaa();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_mhsActionPerformed

    private void btn_perusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perusahaanActionPerformed
        // TODO add your handling code here:
        formPerusahaan n = new formPerusahaan();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_perusahaanActionPerformed

    private void btn_sidangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sidangActionPerformed
        // TODO add your handling code here:
        formSidang n = new formSidang();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_sidangActionPerformed

    private void btn_kpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kpActionPerformed
        // TODO add your handling code here:
        formKP n = new formKP();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_kpActionPerformed

    private void btn_pmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pmbActionPerformed
        // TODO add your handling code here:
        formPembimbing n = new formPembimbing();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_pmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dsn;
    private javax.swing.JButton btn_kp;
    private javax.swing.JButton btn_mhs;
    private javax.swing.JButton btn_perusahaan;
    private javax.swing.JButton btn_pmb;
    private javax.swing.JButton btn_sidang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
